# Docs: https://github.com/Azure/webapps-deploy
# GitHub Actions for Azure: https://github.com/Azure/actions
# Python + Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy FastAPI app to Azure Web App - Sanskars-Assignment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        working-directory: ./backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Optional: Run tests here if you have them
      # - name: Run tests
      #   run: pytest

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            .
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_A5E844B4BD764EF1BBB8D53C81432512 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B0C674FCA4E244FF8B5182BE3BFFF09A }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_B721C979E8F8483AB388BF2673EC2EA7 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Sanskars-Assignment'
          slot-name: 'Production'
          package: .

